$(function(){
	$("#act1").click(function(){
		$("#index").css("display","none");
		$("#brand").css("display","none");
		$("#somato").css("display","block");
		$("#tree").css("display","none");
		$("#photowall").css("display","none");
	});
	$("#act2").click(function(){
		$("#index").css("display","none");
		$("#brand").css("display","none");
		$("#somato").css("display","none");
		$("#tree").css("display","block");
		$("#photowall").css("display","none");
	});
	$("#act3").click(function(){
		$("#index").css("display","none");
		$("#brand").css("display","none");
		$("#somato").css("display","none");
		$("#tree").css("display","none");
		$("#photowall").css("display","block");
	});
	$("#back1").click(function(){
		$("#index").css("display","block");
		$("#brand").css("display","block");
		$("#somato").css("display","none");
		$("#tree").css("display","none");
		$("#photowall").css("display","none");
	});
	$("#back2").click(function(){
		$("#index").css("display","block");
		$("#brand").css("display","block");
		$("#somato").css("display","none");
		$("#tree").css("display","none");
		$("#photowall").css("display","none");
	});
	$("#back3").click(function(){
		$("#index").css("display","block");
		$("#brand").css("display","block");
		$("#somato").css("display","none");
		$("#tree").css("display","none");
		$("#photowall").css("display","none");
	});
	$("#livevideo1").click(function(){
		window.open("http://v.youku.com/v_show/id_XNzg5NDQwNTA0.html");
	});
	$("#livevideo2").click(function(){
		window.open("http://v.youku.com/v_show/id_XNDIzMTM3Njky.html");
	});
	$("#livevideo3").click(function(){
		window.open("http://v.qq.com/page/j/o/g/j01394y02og.html");
	});
	$("#drawvideo2").click(function(){
		window.open("http://v.youku.com/v_show/id_XNDIzMTIzNDQ4.html");
	});
	$("#drawvideo1").click(function(){
		window.open("http://v.youku.com/v_show/id_XNzk0ODcxMjQ0.html?x= ");
	});
});